### PR TITLE
Fixed UnicodeDecodeError: 'ascii' codec can't decode byte'

### PR DESCRIPTION
**Pull request by baruch95**
It was giving me this error so i found a fix.

### CODE REVIEW

**Comment by CoffeeStraw** [comment]
Hello, thank you for your PR!
I've tried the following film, succeding in downloading the file without recieving any error: https://www.vvvvid.it/show/492/pele-the-king-of-football

The title contains an accented letter as well. Can you please post the link that doesn't work for you?

**Comment by baruch95** [comment]
No problem, i've tried with https://www.vvvvid.it/show/786/steinsgate-0 on an Ubuntu 18.04 machine.

**Comment by CoffeeStraw** [comment]
Hello. Sorry for the delay, I will not be able to check that error on my laptop where I have Ubuntu installed until a few days. I've tried it on Windows and it doesn't seem to change anything. Meanwhile, I've worked on the library and completely refactored it, could you please rebase (or probably it is better to totally open another PR)? That way it will be easier for me to merge your commit. Thank you for your help in advance.

**Comment by CoffeeStraw** [comment]
Sorry for the terrible delay. I've managed to search better about that issue on the web. It seems like literal strings are unicode by default in Python3, so it should not be needed to put this "u" prefix. My guess is that you did not use Python3 for the execution. Anyway, I'm closing this issue now.

**Pull request closed without merging**
